//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.6

use sea_orm::entity::prelude::*;
use sea_orm::LinkDef;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "api"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: i32,
    pub name: String,
    pub path: String,
    pub method: String,
    pub code: Option<String>,
    pub icon: Option<String>,
    pub display: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Name,
    Path,
    Method,
    Code,
    Icon,
    Display,
    CreatedAt,
    UpdatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::Name => ColumnType::String(StringLen::None).def().unique(),
            Self::Path => ColumnType::String(StringLen::None).def(),
            Self::Method => ColumnType::String(StringLen::None).def(),
            Self::Code => ColumnType::String(StringLen::None).def().null().unique(),
            Self::Icon => ColumnType::String(StringLen::None).def().null(),
            Self::Display => ColumnType::String(StringLen::None).def().null(),
            Self::CreatedAt => ColumnType::TimestampWithTimeZone.def(),
            Self::UpdatedAt => ColumnType::TimestampWithTimeZone.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl Related<super::role::Entity> for Entity {
    fn to() -> RelationDef {
        super::role_mtm_api::Relation::Role.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::role_mtm_api::Relation::Api.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
