//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.6

pub mod prelude;

pub mod api;
pub mod article;
pub mod category;
pub mod menu;
pub mod role;
pub mod role_mtm_api;
pub mod role_mtm_menu;
pub mod user;
pub mod user_mtm_role;
pub mod utils;
