//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.6

use sea_orm::entity::prelude::*;
use sea_orm::LinkDef;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "user"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: i32,
    pub username: String,
    pub password: String,
    pub email: String,
    pub is_super_user: bool,
    pub active_role_id: Option<i32>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Username,
    Password,
    Email,
    IsSuperUser,
    ActiveRoleId,
    CreatedAt,
    UpdatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::Username => ColumnType::String(StringLen::None).def().unique(),
            Self::Password => ColumnType::String(StringLen::None).def(),
            Self::Email => ColumnType::String(StringLen::None).def().unique(),
            Self::IsSuperUser => ColumnType::Boolean.def(),
            Self::ActiveRoleId => ColumnType::Integer.def().null(),
            Self::CreatedAt => ColumnType::TimestampWithTimeZone.def(),
            Self::UpdatedAt => ColumnType::TimestampWithTimeZone.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl Related<super::role::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_mtm_role::Relation::Role.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_mtm_role::Relation::User.def().rev())
    }
}
impl ActiveModelBehavior for ActiveModel {}
